# Generated by Django 5.0.6 on 2024-05-15 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(default='nombre default', max_length=100)),
                ('sueldo', models.FloatField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('letra', models.CharField(default='A', max_length=100)),
                ('maestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entidades.maestro')),
            ],
        ),
    ]
